---
- name: install postgis
  apt:
    pkg: postgis
    state: present

- name: create database
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ shitsquare_database }}"
    state: present

- name: create database user
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ shitsquare_user }}"
    password: "{{ shitsquare_password }}"
    role_attr_flags: "SUPERUSER"

- name: add postgis to database
  become: yes
  become_user: postgres
  postgresql_ext:
    name: postgis
    db: "{{ shitsquare_database }}"
