---
- name: install postgis
  apt:
    pkg: postgis
    state: present

- name: create database
  become: yes
  become_user: postgres
  postgresql_db:
    name: shitsquaredb
    state: present

- name: create database user
  become: yes
  become_user: postgres
  postgresql_user:
    name: shitsquareuser
    password: shitsquarepassword
    encrypted: true
    role_attr_flags: "SUPERUSER"

- name: add postgis to database
  become: yes
  become_user: postgres
  postgresql_ext:
    name: postgis
    db: shitsquaredb
