---
- name: install postgis
  apt:
    pkg: postgis
    state: present

- name: create database
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ shitsquare_database }}"
    state: present

- name: create database user
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ shitsquare_user }}"
    password: "{{ shitsquare_password }}"
    role_attr_flags: "SUPERUSER"

- name: add postgis to database
  become: yes
  become_user: postgres
  postgresql_ext:
    name: postgis
    db: "{{ shitsquare_database }}"

- name: clone repository
  git:
    repo: 'https://github.com/nachogarcia/shitsquare.git'
    dest: "{{ shitsquare_path }}"
    force: yes

- name: install domain packages
  npm:
    path: "{{ shitsquare_path }}/domain"

- name: install api packages
  npm:
    path: "{{ shitsquare_path }}/api"

- name: initialize database
  shell: node "{{ shitsquare_path }}/domain/DBHandler.js" init
  environment:
    DATABASE_URL: "{{ database_url }}"
- name: create api service
  environment:
    DATABASE_URL: "{{ database_url }}"
  template:
    src=api-service.j2
    dest=/etc/systemd/system/shitsquare-api.service

- name: start api service
  service:
    name: shitsquare-api
    enabled: yes
    state: started
