---
- hosts: all
  vars_files:
    - secrets.yml

  vars:
    - nginx_sites:
      - server_name: api.shitsquare.es
        site_type: "http"
        locations:
          - url: /
            directives:
             - proxy_set_header: Host $host
             - proxy_set_header: X-Real-IP $remote_addr
             - proxy_set_header: X-Forwarded-For $proxy_add_x_forwarded_for
             - proxy_set_header: X-Forwarded-Proto $scheme
             - proxy_pass: http://127.0.0.1:8000
             - proxy_read_timeout: 90

      ansistrano_deploy_to: "{{ shitsquare_path }}"
      ansistrano_keep_releases: 3
      ansistrano_deploy_via: git
      ansistrano_git_repo: 'https://github.com/nachogarcia/shitsquare.git'
      ansistrano_after_update_code_tasks_file: 'deploy/shitsquare/after_update_code.yml'

  roles:
    - base
    - nginx
    - postgresql
    - node.js
    - shitsquare
    - carlosbuenosvinos.ansistrano-deploy
